FROM debian

RUN apt-get update && \
    apt-get install -y curl g++ git gnupg libudev-dev make && \
    curl -fLsS https://deb.nodesource.com/setup_8.x | bash - && \
    apt-get install -y nodejs && \
    mkdir /usr/local/src/open-zwave && \
    curl -fLsS \
      https://api.github.com/repos/OpenZWave/open-zwave/tarball/master | \
      tar xz -C /usr/local/src/open-zwave --strip-components 1 && \
    cd /usr/local/src/open-zwave && \
    make && \
    make install

WORKDIR /code

COPY package-lock.json package.json ./
RUN npm install

ENV LD_LIBRARY_PATH /usr/local/lib64

CMD ["bin/run"]
